project:
  type: website

lang: pt-BR 
# page-layout: full

filters: 
  - ajuste-data.lua

website:
  announcement: 
    icon: exclamation-octagon
    dismissable: false
    content: "**Atenção** - Este site é apenas um protótipo/estudo de conceito. Não há informações relevantes aqui! Ainda..."
    type: danger
    position: above-navbar
    
  title: "Ensino e Aprendizagem no DC"
  favicon: logo-dc.png
  reader-mode: true
  bread-crumbs: true

  page-footer: |
    [Departamento de Computação](https://www.dc.ufscar.br){target="_blank"} - [UFSCar](https://www.ufscar.br){target="_blank"}

  navbar:
    logo: logo-dc.png
    search: true
    left:
      # - text: "Metodologias ativas"
      #   menu:
      #     - text: "Visão geral"
      #       href: metodologias-ativas/metodologias-ativas.qmd
      # - text: "Construção"
      #   href: construcao/index.html
      # - text: "Metodologias ativas"
      #   href: metodologias-ativas/index.html
      # - text: "Avaliação"
      #   href: avaliacao/index.html
      # - text: "Mais"
      #   menu:
      #     - casos/index.qmd
      #     - material.qmd
      - sobre.qmd

format:
  html:
    # fontsize: 14pt
    theme:
      light: yeti
      dark: cyborg

    css: styles.css
    toc: true

  # pdf:
  #   latex-output-dir: out/
  #   pdf-engine: pdflatex