project:
  type: website
  resources: 
    - CNAME

lang: pt-BR 

filters: 
  - ajuste-data.lua

website:
  # announcement: 
  #   icon: exclamation-octagon
  #   dismissable: false
  #   content: "**Atenção** - Este site está sendo estruturado. Tenha paciência."
  #   type: danger
  #   position: above-navbar
    
  title: "EADC - Ensino e Aprendizagem no DC"
  favicon: logo-dc.png
  site-url: https://eadc.ufscar.br
  repo-url: https://github.com/ea-dc/ea-dc.github.io
  page-navigation: true
  reader-mode: true
  # google-analytics: true
  bread-crumbs: true

  page-footer: |
    [Departamento de Computação](https://www.dc.ufscar.br){target="_blank"} - [UFSCar](https://www.ufscar.br){target="_blank"}

  navbar:
    logo: logo-dc.png
    search: true
    left:
      # - text: "Metodologias ativas"
      #   menu:
      #     - text: "Visão geral"
      #       href: metodologias-ativas/metodologias-ativas.qmd
      # - text: "Construção"
      #   href: construcao/index.html
      - text: "Metodologias ativas"
        href: metodologias-ativas/index.html
      # - text: "Avaliação"
      #   href: avaliacao/index.html
      - text: "Material"
        href: material/index.qmd
      - text: "Relatos"
        href: relatos/index.qmd
      # - sobre.qmd

format:
  html:
    # fontsize: 14pt
    theme:
      light: yeti
      dark: solar

    css: styles.css
    toc: true

  # pdf:
  #   latex-output-dir: out/
  #   pdf-engine: pdflatex