---
title: "Ensino e Aprendizagem no DC"
listing:
    id: acoes
    contents:
        - acoes/2*.qmd  # arquivos que começam com 2 (e.g., 2025-....)
    sort: date desc
    type: default
    max-items: 4
    categories: false
    sort-ui: false
    filter-ui: false
    fields: [author, title, date, description]
page-layout: full
title-block-bannerrR: false
---

:::: {.columns}

::: {.column width="50%"}
## O que é este site?

Este site é dedicado ao planejamento do ensino e aprendizagem no DC!

No final de 2024 um grupo de docentes do [Departamento de Computação](http://www.dc.ufscar.br) se uniu para discutir, tão amplamente quanto possível, as relações entre o ensino e a aprendizagem para os cursos de [Ciência da Computação](https://www.dc.ufscar.br/gradua%C3%A7%C3%A3o/ci%C3%AAncia-da-computa%C3%A7%C3%A3o) e [Engenharia de Computação](https://www.ec.ufscar.br/).

Sua criação foi feita pelo Conselho Departamental na 2ª Reunião Ordinária de 2025 ocorrida em 19 de fevereiro de 2025.

Formação:

* Daniel Lucrédio
* Edilson Kato
* Fredy Valente
* Jander Moreira
* Marcela Ribeiro
* Roberto Ferrari

Os objetivos do EADC compreendem:

* Capacitação docente;
* Promoção da melhoria do ensino e da aprendizagem;
* Integração de suas ações aos Projetos Pedagógicos de Curso orientados por competências.

A formação do grupo é voluntária e a participação de outros docentes, seja integrando-se ao grupo ou por participações ocasionais, é bem-vinda e, por que não?, incentivada.
:::

::: {.column width="5%"}
:::


::: {.column width="35%"}
::: {.callout}
## O que acontece por aqui?

::: {#acoes}
:::

[Todas as ações do grupo!](acoes/index.qmd)

:::
:::

::::