---
title: Fishbowl
categories:
  # Tamanho e perfil da turma
  - "Turmas médias"
  - "Turmas grandes"
  
  # Tamanho do grupo de trabalho
  - "Turma inteira"
  
  # Espaço físico
  - "Sala ampla"
  - "Sala flexível"
  
  # Tempo
  - "Pontual"
  
  # Recursos humanos
  - "Facilitador único"
  
  # Preparação prévia
  - "Sem preparação prévia"
  
  # Interação
  - "Síncrona"
  
  # Modalidade
  - "Presencial"
---

A metodologia Fishbowl é uma técnica de discussão em grupo que promove o diálogo aberto e a escuta ativa. Um pequeno grupo discute um tema no centro, enquanto os demais observam ao redor. Há uma cadeira vaga que permite a entrada de novos participantes, desde que alguém do centro ceda o lugar. O objetivo é estimular a participação ordenada, o respeito às falas e a troca de ideias de forma colaborativa. É útil em contextos educacionais, organizacionais e em decisões coletivas.

Sugestão de leitura:

* [O fishbowl como estratégia de discussão e aprendizagem ativa no ensino presencial e on-line](https://www.researchgate.net/publication/355637220_O_FISHBOWL_COMO_ESTRATEGIA_DE_DISCUSSAO_E_APRENDIZAGEM_ATIVA_NO_ENSINO_PRESENCIAL_E_ON-LINE){target="_blank"}

# Sobre a aplicação

* Turmas médias e grandes: Fishbowl é eficaz para grupos maiores, onde o público participa como observador ou membro do "anel externo".
* Turma inteira: A atividade envolve a turma toda, mas o debate ocorre em grupos internos.
* Sala ampla e flexível: Necessário espaço para organizar os círculos (interno e externo).
* Pontual: Normalmente uma sessão única ou evento.
* Facilitador único: Geralmente conduzida por um mediador/facilitador.
* Sem preparação prévia: A maioria das vezes não exige preparação antecipada.
* Síncrona: A interação ocorre em tempo real.
* Presencial: A forma mais comum e efetiva, pois depende da disposição física dos participantes.